### PR TITLE
docs: Build Docker Images Locally

### PR DESCRIPTION
**Pull request by dlsnyder8**
**Summary**
This PR adds a way to build images locally in the Dockerfile
- Add `build` field to web, bot, and api images
- Updates the readme to tell people how to build images locally

### CODE REVIEW

**Comment by chamburr** [comment]
I think the better way is to add back the build contexts to the docker compose file (https://github.com/chamburr/modmail/commit/7201ba0ed3d8bfd365b01484213596057533d0ec), then use `docker compose build` and `docker compose up -d`. Please help to check if that works. 😄

**Comment by dlsnyder8** [comment]
Yeah that makes more sense. I made the build script first, then changed the docker compose file after. 

The last commit builds successfully - changed the readme to accommodate the change.

**Comment by chamburr** [comment]
Actually, I meant by putting the build context into the current `docker-compose.yml` file, so we won't have duplicate code. I vaguely remember that image and build can be both present, and it will default to pulling the image. The build command should force a local build. Please correct me if I'm wrong.

**Comment by dlsnyder8** [comment]
"When a build subsection is present for a service, Compose ignores the image attribute for the corresponding service, as Compose can build an image from source."

It would always build the image from scratch if it was done that way per the docs. I was trying to avoid any breaking changes with the split, and having different docker-compose files for different purposes is acceptable coding style. 

I was avoiding changing the original docker compose to avoid breaking changes if people relied on it.

**Comment by chamburr** [comment]
Hmm... https://docs.docker.com/compose/compose-file/build/#consistency-with-image

**Comment by dlsnyder8** [comment]
Hmmm. I stand corrected. Will update

**Comment by dlsnyder8** [comment]
You were technically correct - but even if you use `docker-compose build` it'll still pull the image from Docker Hub using `docker-compose up`. The only way I could get around it was by adding an environment variable that chooses between the dev tag and the latest tag, which isn't a bad solution. 

It also prevents any issues with backwards compatibility because if the `DOCKER_TAG` var isn't defined in `.env` it'll default to `latest`, so you only need to add the var if you plan on doing any local testing.

**Pull request merged**
