### PR TITLE
feat: rewrite bot

### PR DESCRIPTION
**Pull request by waterflamev8**
it's pretty bad right now ._.

### CODE REVIEW

**Comment by xrowii** [comment]
YOU DIDNT FIX

**Comment by xrowii** [comment]
CEN HAN ANGWY

**Comment by waterflamev8** [comment]
yeah LOL

**Comment by Shadowof-botof** [comment]
Hello

**Comment by Shadowof-botof** [comment]
Fuck me fuck me! Sex I wan't to fuck cum

**Review by kraniet888 — COMMENTED** [review]
R.I.P

**Pull request merged**
