### PR TITLE
Premium alert message update

### PR DESCRIPTION
**Pull request by SnowyJaguar1034**
I updated the popup menu that users get when they click purchase. I did this because some people on the support server said it was confusing which is why they did not join the support server before buying premium. The old message was:
```
<p>
                        Before proceeeding to payment, please join our
                        <a href="/support" target="_blank" class="link-dark">support server</a> to receive the role and
                        rewards.
                    </p>
```

and the new message is:
```
<p>
                        Please join our <a href="/support" target="_blank" class="link-dark"> support server</a> <strong>BEFORE</strong> purchasing so that your premiun can be successfully enabled.
                    </p>
                    <p>
                        <i>You will not receive your perks propelry if you do not join the supposrt server.</i>
                    </p>
```

### CODE REVIEW

**Comment by dlsnyder8** [comment]
Typo:
"Properly" not "propelry"

**Review by dlsnyder8 — CHANGES_REQUESTED** [review]
Typos:
"Properly" not "propelry"
"Support" not "supposrt"
"Premium" not "premiun"

**Comment by SnowyJaguar1034** [comment]
Thanks for pointing out my dyslexic spelling 😅 I'll fix those tommorw.

**Comment by SnowyJaguar1034** [comment]
Fixed those spelling mistakes, let me know if there are any more errors in what I have added but I think it should be error-free now.

**Comment by Foxtrek64** [comment]
I don't like this solution. While I agree the message should be updated to reflect that you need to be in the server to get your perks (imo that should change too), the correct solution should be to change the user join handler so that it checks if they have premium and, if so, awards the appropriate role.

I'm not sure where this data lives or how to access it, but it may be worth investigating and implementing both changes at the same time.

**Comment by chamburr** [comment]
> the correct solution should be to change the user join handler so that it checks if they have premium and, if so, awards the appropriate role.

I agree with this, will need to look into how to check if a user has premium after joining. In addition, it could also be good to show a message on the payment success page too.

Anyway, I'll likely have to merge #62 before this, and that's taking a while because I haven't had enough time to work on that yet.

**Comment by chamburr** [comment]
This is superseded in e0b0bce2776634c7ea2d36f2ea642a04d9c20009.

**Pull request closed without merging**
