### PR TITLE
Default server

### PR DESCRIPTION
**Pull request by dlsnyder8**
Fix intents to include guild member intent
Add default server option to avoid awkward "verify" message
random auto-formatting (thanks vs code)
set logging channels to be 0 so logging is turned off by default

### CODE REVIEW

**Comment by dlsnyder8** [comment]
@chamburr when you have a sec to approve

**Comment by chamburr** [comment]
Why is member intent needed?

**Comment by dlsnyder8** [comment]
https://github.com/chamburr/modmail/blob/88ec1e9b24020e0b7af04e1f4229a232674c27f1/cogs/direct_message.py#L31

and a couple other `guild.fetch_member` references scattered throughout the code

**Comment by chamburr** [comment]
That does not require member intent in the gateway.

**Comment by dlsnyder8** [comment]
I could have sworn that it was necessary to have that but alright.

**Pull request merged**
