### PR TITLE
feat(bot): Add Author to Snippets

### PR DESCRIPTION
**Pull request by dlsnyder8**
**Summary**
Adding an Author to the person who creates a snippet. 
Adds a migration to add the field to existing database, and defaults the field to `NULL`. 
Shows who created the snippet in the `viewsnippet` command

**Related issue(s)**
Suggestion #530

**Additional context**
Ignoring the alias suggestion - You can just create multiple snippets (accomplishes same thing w/ no code changes)
Ignoring adding title/content field for use in embed. Can be revisited in d.py2.1+ migration when slash commands are introduced
Ignoring `{username:<user id>}` mention - you can just ping a role or use `<@userid>` syntax. Same w/ channel and role mentions

-----
Updated lint.sh to only lint `cogs/`, `classes/`, and `utils/`. Otherwise it was linting virtual env folder

### CODE REVIEW

**Comment by chamburr** [comment]
For linting, it's preferable to use `flake8 --extend-exclude` for future compatibility and to lint python files in the root folder.

**Comment by dlsnyder8** [comment]
Can do. Just assumes that everyone names their virtual env folders the same.

**Comment by SnowyJaguar1034** [comment]
> Ignoring the alias suggestion - You can just create multiple snippets (accomplishes same thing w/ no code changes)

The reason I suggested the alias option is to reduce overall db entries and duplication. It is also more user-friendly because, at the moment, if someone has a snippet they want to have multiple names, they need to recreate it multiple times, but what happens when they need to update it? They need to delete all instances of that snippet and re-add each one; however, if there was an alias system, then they only need to recreate the actual snippet once and then relink the alias'.

The bot could tell them what the previous aliases' were when they remove a snippet. and then when they link alias', they could have up to (for example) 5 alias' options, denoted by args in the command like `snippet alias alias1 alias2 etc`.

My first implementation idea was that a new column would need to be added to the database to contain a list of alias'; however, I have since realised that might be hard to index and retrieve, so perhaps a new column with a True/False of 'Is Alias' and then if 'False' then it stores it as a normal snippet and if 'True' then it only stores one of the snippet fields (presumably the title as it's the first arg) and then it sends that back to the db to retrieve the actual snippet.

Does that make the reason for the alias feature more understandable? I'm trying to improve the end-user experience because there are a few aspects of the bot that, in my opinion, aren't very intuitive to users, new and old.

**Comment by dlsnyder8** [comment]
@SnowyJaguar1034 

Honestly I just think it's unnecessary. Having more than 1 alias is unlikely, and if staff are using `alias2` >>> `alias1`, then you should just remove `alias1` (assuming you just made 2 snippet entries w/ current commands).

I also see no functional reason why you would have more than 1 alias for a command, and certainly not 3 or 4. I think it introduces indexing and caching problems that just are not worth it as well.

And if someone has 2 snippets with the same content and needs to update it, then it would add 5 seconds to copy and paste the content into a new`=snippetadd` command.

**Pull request merged**
