### PR TITLE
feat(bot): Specify you can ping the bot as prefix

### PR DESCRIPTION
**Pull request by Scyye**
**Summary**
Add onto the header of the pages of `=help`, that `@ModMail [command]` is valid.

**Related issue(s)**
[Suggestion #546](https://discord.com/channels/576016832956334080/576765354051633178/1177636249012547697)

**Additional context**
N/A

### CODE REVIEW

**Comment by Scyye** [comment]
Why does it list all those old ass commits every time-

**Comment by dlsnyder8** [comment]
@chamburr thoughts? wording seems off to me but I can't think of a way to make it more clear that isn't overly verbose

**Comment by Scyye** [comment]
yea that was my thought to, hopefully chamburger has a better idea

**Comment by Scyye** [comment]
I changed the wording a bit

**Comment by Scyye** [comment]
@chamburr thoughts?

**Comment by chamburr** [comment]
I don't like the wording and also can't think of better alternatives...

**Comment by Scyye** [comment]
Ill close this for now. I still think it'd be a good idea to come back to this at some point when we can think of an improved wording.

**Pull request closed without merging**
