### PR TITLE
FEATURE: Custom Greeting/Closing tags

### PR DESCRIPTION
**Pull request by LyricWulf**
FEATURE: Adding custom flag {uid} to replace sent custom greet/close with their own user ID
Signed-off-by: LyricWulf <lyric@lyricwulf.com>

### CODE REVIEW

**Comment by CHamburr** [comment]
Please don't include the commit for #2 here. Also it would be great if you can add more flags {username} {usertag} {userid} and reuse the code.

**Comment by LyricWulf** [comment]
Done and done! also used a dictionary so it's scalable, instead of reusing the code

**Comment by CHamburr** [comment]
I think you misunderstood what I meant. Currenty you have to update 2 dicts whenever you want to add a tag. No worries though, I'll fix it.

**Comment by CHamburr** [comment]
591515a

**Pull request closed without merging**
