### PR TITLE
FEATURE: Send all attachments for loggingplus enabled.

### PR DESCRIPTION
**Pull request by LyricWulf**
Sends all seen attachments on loggingplus.
Not sure about file size limits, but there could be a check incorporated later.
Signed-off-by: LyricWulf <lyric@lyricwulf.com>

### CODE REVIEW

**Comment by CHamburr** [comment]
It's generally not a good idea to do this because there can be infinite files in each ticket and yeah file size limit is also an issue

**Comment by CHamburr** [comment]
Including attachment links from the DM would be a much better choice. @LyricWulf Do you think you can edit this PR a bit?

**Comment by LyricWulf** [comment]
Done! They are now all listed in the log file.

**Comment by CHamburr** [comment]
I don't think attachments are preserved on DIscord's CDN after the channel gets deleted. So the attachment links must be from the DM channel...

**Comment by CHamburr** [comment]
Got it done in 591515a

**Pull request closed without merging**
