### PR TITLE
fix(core): Changes whitelist/blacklist command check from MemberConverter to UserConverter

### PR DESCRIPTION
**Pull request by SnowyJaguar1034**
**Summary**
Changed the whitelist command to do a check against `discord.user` instead of the custom `MemberConverter`. This is because if a member is not in the server then the bot can not resolve them to have them removed from the blacklist.

This could be superseded by a `USerConverter` or a check in the `MemberConveter to check if the user is fectable.

**Related issue(s)**
#160 

**Additional context**
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by chamburr** [comment]
Yes please just use the UserConverter. Remove the irrelevant code in docker-compose.yml as well please.

**Comment by SnowyJaguar1034** [comment]
> Yes please just use the UserConverter. Remove the irrelevant code in docker-compose.yml as well please.

Oh there's a existing UserConverter.

Yeah the docker-compose changes were an accidental commit, meant to go to a different branch so I'm not sure why they popped up here

**Comment by SnowyJaguar1034** [comment]
> Yes please just use the UserConverter. Remove the irrelevant code in docker-compose.yml as well please.

Yeah i can't seem to see any UserConverter, there's a MemberConverter which is what is currently used and therefore causing the problem

**Comment by SnowyJaguar1034** [comment]
> > Yes please just use the UserConverter. Remove the irrelevant code in docker-compose.yml as well please.
> 
> Yeah i can't seem to see any UserConverter, there's a MemberConverter which is what is currently used and therefore causing the problem

Okay never mind I was being blind, found it here https://github.com/chamburr/modmail/blob/fcad83b4508419aeb40fa169490ef975d0636194/utils/converters.py#L113-L122

**Pull request merged**
