### PR TITLE
feat: Command only mode

### PR DESCRIPTION
**Pull request by dlsnyder8**
**Summary**
Adds a command which will enable servers to set a `command only` mode on tickets, where either the `=reply` or `=areply` commands are required to send a response in a ticket.

**Related issue(s)**
Issue #99

### CODE REVIEW

**Comment by dlsnyder8** [comment]
This commit relies on PR#115 being accepted and the `commandrequired` flag being 12th in the list. 

`commandrequired` should default to False for all servers in schema

**Comment by dlsnyder8** [comment]
Also accidentally added two extra commits. Part of already accepted PR (sorry cham github funky)

**Comment by dlsnyder8** [comment]
#114 and #116 will have conflicts with the database schema as both add fields. Will need to remedy before full integration

**Comment by dlsnyder8** [comment]
Removed the better optimization commit

**Review by chamburr — CHANGES_REQUESTED** [review]

**Comment by dlsnyder8** [comment]
Lol. I was expecting #98 to get pushed out first as that would use data[11]. oopsies

**Review by chamburr — APPROVED** [review]

**Pull request merged**
